# Generated by Django 5.1.1 on 2024-09-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogoMemoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='jogadas',
            field=models.IntegerField(max_length=100),
        ),
    ]
