# Generated by Django 5.1.1 on 2024-09-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogoMemoria', '0002_alter_jogador_jogadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='jogadas',
            field=models.CharField(max_length=20),
        ),
    ]
